<a href="https://colab.research.google.com/github/slisovych/machine_learning_hometasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [28]:
import numpy as np

vector = np.random.rand(10)
vector

array([0.88298688, 0.95895096, 0.99125991, 0.80729763, 0.47111365,
       0.23068212, 0.21253446, 0.98642267, 0.94907058, 0.27676307])

In [6]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [29]:
vector.shape, matrix.shape

((10,), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [31]:
vector_round = np.round(vector + 10, 2)
vector_round

array([10.88, 10.96, 10.99, 10.81, 10.47, 10.23, 10.21, 10.99, 10.95,
       10.28])

In [8]:
matrix_mult = matrix * 2
matrix_mult

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [32]:
vector_square = vector ** 2
vector_square

array([0.77966583, 0.91958694, 0.9825962 , 0.65172946, 0.22194807,
       0.05321424, 0.0451709 , 0.97302968, 0.90073496, 0.0765978 ])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [11]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [16]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [20]:
result_matrix_c = result_matrix.dot(C)
result_matrix_c

array([[0.5202],
       [0.2846]])

In [26]:
result_matrix_d = result_matrix.dot(D)
result_matrix_d #Матриця D просто міняє місцями стовпці матриці result_matrix

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
result_matrix_t = result_matrix.T
result_matrix_t

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [34]:
vector_t = vector.T
vector_t
#операція транспонування не змінює його форму

array([0.88298688, 0.95895096, 0.99125991, 0.80729763, 0.47111365,
       0.23068212, 0.21253446, 0.98642267, 0.94907058, 0.27676307])

In [35]:
column_vector = np.expand_dims(vector, axis=1)
column_vector
# перетворився у вектор-стовпець

array([[0.88298688],
       [0.95895096],
       [0.99125991],
       [0.80729763],
       [0.47111365],
       [0.23068212],
       [0.21253446],
       [0.98642267],
       [0.94907058],
       [0.27676307]])

In [39]:
column_vector_t = column_vector.T
print ("Транспонування:", column_vector_t)

print ("Розмірність:", column_vector_t.shape)

Транспонування: [[0.88298688 0.95895096 0.99125991 0.80729763 0.47111365 0.23068212
  0.21253446 0.98642267 0.94907058 0.27676307]]
Розмірність: (1, 10)
